spring.shell.interactive.enabled: false

ssh:
  shell:
    prompt:
      color: cyan
      text: 'basic::>'
    user: user
    password: password
    commands:
      actuator:
        create: false
      jmx:
        create: false
      datasource:
        create: false
      stacktrace:
        create: false
      tasks:
        create: false
      system:
        create: false
      script:
        create: false
      manage-sessions:
        create: false

logging:
  level:
    com.github.choseongah: debug
