ssh:
  shell:
    prompt:
      color: bright
      text: 'basic::>'
    user: user
    password: password

spring:
  shell:
    interactive:
      enabled: false

server:
  port: 18080

logging:
  level:
    io.github.choseongah: debug
