ssh:
  shell:
    authentication: security
    auth-provider-bean-name: sshAuthenticationManager
    authorized-public-keys: classpath:.ssh/authorized.keys
    commands:
      actuator:
        enable: true
      jmx:
        enable: true
      datasource:
        enable: true
      stacktrace:
        enable: true
      tasks:
        enable: true
      system:
        enable: true
      script:
        enable: true
      manage-sessions:
        enable: true
    host: 0.0.0.0
    port: 10045
    shared-history: false
    history-directory: ./target/ssh-history

spring:
  jmx:
    enabled: true
  first-datasource:
    url: jdbc:h2:mem:test-db-first
  second-datasource:
    url: jdbc:h2:mem:test-db-second
  main.lazy-initialization: true
  shell:
    interactive:
      enabled: false

management:
  endpoints:
    access:
      default: unrestricted
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    heapdump:
      access: unrestricted
    shutdown:
      access: unrestricted
  info:
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true

info:
  app:
    name: ssh-shell-spring-boot-complete-sample
    description: Complete sample

logging:
  level:
    com.github.choseongah: debug
